### ISSUE TITLE
What means each tag (B-C, B-AS, ...)?

### ISSUE THREAD

**Issue by judsonbsilva** [fabioacl/PortugueseClinicalNER#1]
Quero saber o significado de cada tag pra tentar usar os textos taggeados

**Comment by fabioacl** [comment]
Viva,
O significado de cada tag está explicado no artigo disponível em https://www.aclweb.org/anthology/W19-5024, sendo que o B significa begin de uma dada entidade e o I significa inside uma dada entidade.

Cumprimentos,
Fábio
